
import java.util.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
public class journeyplan extends javax.swing.JFrame {

    /**
     * Creates new form journeyplan
     */
    public journeyplan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        tf8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        tf10 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tf11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tf12 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf13 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("From   :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("To  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Date  :");

        tf1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tf2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tf3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("SEARCH  TRAINS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Selected  Train   :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Seats  Available  :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Departure :");

        tf4.setEditable(false);
        tf4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tf5.setEditable(false);
        tf5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tf6.setEditable(false);
        tf6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox1.setText("AC");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox2.setText("Sleeper");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Ticket Cost  :");

        tf8.setEditable(false);
        tf8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Rs.");

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 51, 51));
        jButton10.setText("BOOK  TICKET");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Starting  Point  :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Stopping  Points  :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Ending  Point  :");

        tf9.setEditable(false);
        tf9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        tf10.setEditable(false);
        tf10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(204, 0, 51));
        jButton11.setText("BACK ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Arrival  :");

        tf7.setEditable(false);
        tf7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAIN NO.", "TRAINS' NAME", "DEPARTURE", "TRAVEL TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDragEnabled(true);
        jTable1.setIntercellSpacing(new java.awt.Dimension(5, 10));
        jTable1.setRowHeight(100);
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Enter preferred train no  :");

        tf11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("GO  TO  WALLET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tf12.setEditable(false);
        tf12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("go back and again\npress plan journey\nto check train from \nother stations.");
        jScrollPane3.setViewportView(jTextArea1);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("PNR   :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Travel  Time   :");

        tf13.setEditable(false);
        tf13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jCheckBox1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox2))
                                .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf10)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf7)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(tf12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
String f=tf1.getText(); 
String t=tf2.getText();
String tn=tf11.getText();
//1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
if( (f.equalsIgnoreCase("kanpur")&&t.equalsIgnoreCase("jhansi"))||(f.equalsIgnoreCase("jhansi")&&t.equalsIgnoreCase("kanpur")))
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        PreparedStatement ps=c.prepareStatement("select * from kanpur_jhansi where train_no=?");
        ps.setString(1,tn);
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("bhopal"))||(f.equalsIgnoreCase("bhopal")&& t.equalsIgnoreCase("moradabad")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from moradabad_bhopal where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("moradabad")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from moradabad_newdelhi where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_newdelhi where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("goa"))||(f.equalsIgnoreCase("goa")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_goa where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bangalore"))||(f.equalsIgnoreCase("bangalore")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_bangalore where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("hyderabad"))||(f.equalsIgnoreCase("hyderabad")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_hyderabad where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("shillong"))||(f.equalsIgnoreCase("shillong")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_shillong where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_bombay where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//10***************************************10*****************************************************************
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("new delhi")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from newdelhi_bombay where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//11*****************************************************************************************11**********
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("jaipur"))||(f.equalsIgnoreCase("jaipur")&& t.equalsIgnoreCase("new delhi")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from newdelhi_jaipur where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//12****************************************************+++++++++++++++++++++++++++++++++++12
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("srinagar"))||(f.equalsIgnoreCase("srinagar")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_srinagar where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//13**************************************13+++++++++++++++++++++++++++++++++++++++++++
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("chandigarh"))||(f.equalsIgnoreCase("chandigarh")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_chandigarh where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(5));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
this.dispose();
        home h=new home();
h.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String f=tf1.getText();
String t=tf2.getText();
// 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("jhansi"))||(f.equalsIgnoreCase("jhansi")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_jhansi ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("bhopal"))||(f.equalsIgnoreCase("bhopal")&& t.equalsIgnoreCase("moradabad")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from moradabad_bhopal ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("moradabad")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from moradabad_newdelhi ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
           String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_newdelhi ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("goa"))||(f.equalsIgnoreCase("goa")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_goa ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//66666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bangalore"))||(f.equalsIgnoreCase("bangalore")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_bangalore ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("hyderabad"))||(f.equalsIgnoreCase("hyderabad")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_hyderabad ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//8888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("shillong"))||(f.equalsIgnoreCase("shillong")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_shillong ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_bombay ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//10101010101010*1010101010101010101010101010101010010101010010101001010101001010101010100101010101
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("new delhi")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from newdelhi_bombay ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//11************************************************************************************************************11
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("jaipur"))||(f.equalsIgnoreCase("jaipur")&& t.equalsIgnoreCase("new delhi")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from newdelhi_jaipur ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//12********************************************************************12*******************************************
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("srinagar"))||(f.equalsIgnoreCase("srinagar")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_srinagar ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//13******************++++++++++++++++++++++++********************************13*************************
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("chandigarh"))||(f.equalsIgnoreCase("chandigarh")&& t.equalsIgnoreCase("kanpur")) )
{
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("select * from kanpur_chandigarh ");
         while(rs.next())
        {
            String tn=rs.getString(1);
            String tr=rs.getString(2);
            String de=rs.getString(3);
            String tt=rs.getString(11);
            m.addRow(new Object[]{tn,tr,de,tt});
        }
         c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String tn=tf11.getText();
String f=tf1.getText();
String t=tf2.getText();
//1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("jhansi"))||(f.equalsIgnoreCase("jhansi")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_jhansi where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("bhopal"))||(f.equalsIgnoreCase("bhopal")&& t.equalsIgnoreCase("moradabad")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from moradabad_bhopal where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("moradabad")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from moradabad_newdelhi where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_newdelhi where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("goa"))||(f.equalsIgnoreCase("goa")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_goa where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bangalore"))||(f.equalsIgnoreCase("bangalore")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_bangalore where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("hyderabad"))||(f.equalsIgnoreCase("hyderabad")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_hyderabad where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("shillong"))||(f.equalsIgnoreCase("shillong")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_shillong where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_bombay where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//10***************************************10*****************************************************************
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("new delhi")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from newdelhi_bombay where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//11*****************************************************************************************11**********
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("jaipur"))||(f.equalsIgnoreCase("jaipur")&& t.equalsIgnoreCase("new delhi")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from newdelhi_jaipur where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//12****************************************************+++++++++++++++++++++++++++++++++++12
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("srinagar"))||(f.equalsIgnoreCase("srinagar")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_srinagar where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//13**************************************13+++++++++++++++++++++++++++++++++++++++++++
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("chandigarh"))||(f.equalsIgnoreCase("chandigarh")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_chandigarh where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if (rs.next())
    {
        tf4.setText(rs.getString(10));
        tf5.setText(rs.getString(2));
        tf6.setText(rs.getString(3));
        tf7.setText(rs.getString(4));
        tf9.setText(rs.getString(7));
        ta1.setText(rs.getString(8));
        tf10.setText(rs.getString(9));
        tf13.setText(rs.getString(11));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "not found");
        tf11.setText("");
    }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
String f=tf1.getText(); 
String t=tf2.getText();
String tn=tf11.getText();
//1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
if( (f.equalsIgnoreCase("kanpur")&&t.equalsIgnoreCase("jhansi"))||(f.equalsIgnoreCase("jhansi")&&t.equalsIgnoreCase("kanpur")))
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        PreparedStatement ps=c.prepareStatement("select * from kanpur_jhansi where train_no=?");
        ps.setString(1,tn);
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("bhopal"))||(f.equalsIgnoreCase("bhopal")&& t.equalsIgnoreCase("moradabad")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from moradabad_bhopal where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("moradabad")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from moradabad_newdelhi where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_newdelhi where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("goa"))||(f.equalsIgnoreCase("goa")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_goa where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bangalore"))||(f.equalsIgnoreCase("bangalore")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_bangalore where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("hyderabad"))||(f.equalsIgnoreCase("hyderabad")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_hyderabad where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("shillong"))||(f.equalsIgnoreCase("shillong")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_shillong where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_bombay where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//10***************************************10*****************************************************************
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("new delhi")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from newdelhi_bombay where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//11*****************************************************************************************11**********
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("jaipur"))||(f.equalsIgnoreCase("jaipur")&& t.equalsIgnoreCase("new delhi")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from newdelhi_jaipur where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//12****************************************************+++++++++++++++++++++++++++++++++++12
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("srinagar"))||(f.equalsIgnoreCase("srinagar")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_srinagar where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}
//13**************************************13+++++++++++++++++++++++++++++++++++++++++++
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("chandigarh"))||(f.equalsIgnoreCase("chandigarh")&& t.equalsIgnoreCase("kanpur")) )
{
    try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("select * from kanpur_chandigarh where train_no=?");
    ps.setString(1,tn);
    ResultSet rs=ps.executeQuery();
    if(rs.next())
        {
            tf8.setText(rs.getString(6));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "check database table :-(");
        }
    c.close();
}
catch (Exception e)
{
    e.printStackTrace();
}
}        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
String tc=tf8.getText();
// the way to get the pnr************************************************






    String num="0123456789";
Random r=new Random();
char[] pnr=new char[10];
for(int i=0;i<10;i++)
{
    pnr[i]=num.charAt(r.nextInt(num.length()));
}
tf12.setText(String.valueOf(pnr));

//****************************************************here it ends,,,,..........
//the way to reduce the seats by one on booking************************************************
        int a=Integer.parseInt(tf4.getText());
int b=a-1;
String newseats=String.valueOf(b);
tf4.setText(newseats);
String f=tf1.getText();
String t=tf2.getText();
String tn=tf11.getText();
//1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
if( (f.equalsIgnoreCase("kanpur")&&t.equalsIgnoreCase("jhansi"))||(f.equalsIgnoreCase("jhansi")&&t.equalsIgnoreCase("kanpur")))
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_jhansi set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("bhopal"))||(f.equalsIgnoreCase("bhopal")&& t.equalsIgnoreCase("moradabad")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update moradabad_bhopal set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
if((f.equalsIgnoreCase("moradabad")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("moradabad")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update moradabad_newdelhi set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("new delhi"))||(f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_newdelhi set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("goa"))||(f.equalsIgnoreCase("goa")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_goa set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bangalore"))||(f.equalsIgnoreCase("bangalore")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_bangalore set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("hyderabad"))||(f.equalsIgnoreCase("hyderabad")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_hyderabad set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("shillong"))||(f.equalsIgnoreCase("shillong")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_shillong set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_bombay set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//10***************************************10*****************************************************************
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("bombay"))||(f.equalsIgnoreCase("bombay")&& t.equalsIgnoreCase("new delhi")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update newdelhi_bombay set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//11*****************************************************************************************11**********
if((f.equalsIgnoreCase("new delhi")&& t.equalsIgnoreCase("jaipur"))||(f.equalsIgnoreCase("jaipur")&& t.equalsIgnoreCase("new delhi")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update newdelhi_jaipur set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//12****************************************************+++++++++++++++++++++++++++++++++++12
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("srinagar"))||(f.equalsIgnoreCase("srinagar")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_srinagar set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}
//13**************************************13+++++++++++++++++++++++++++++++++++++++++++
if((f.equalsIgnoreCase("kanpur")&& t.equalsIgnoreCase("chandigarh"))||(f.equalsIgnoreCase("chandigarh")&& t.equalsIgnoreCase("kanpur")) )
{
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
        Statement ps=c.createStatement();
        ps.executeUpdate("update kanpur_chandigarh set seats_available='"+newseats+"' where train_no ='"+tn+"'" );
        JOptionPane.showMessageDialog(null,"seats updated");
        c.close();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
}        






JOptionPane.showMessageDialog(null,"We got the PNR "+"\n"+"pls note the PNR");
// inserting values in a table mybooking *************************************************************


String pn=tf12.getText();
String d=tf3.getText();
String tname=tf5.getText();
String tno=tf11.getText();
String fr=tf1.getText();
String to=tf2.getText();
String de=tf6.getText();
String ar=tf7.getText();
String co=tf8.getText();
String tt=tf13.getText();
try
{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    Connection c=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","java");
    PreparedStatement ps=c.prepareStatement("insert into mybooking values(?,?,?,?,?,?,?,?,?,?)");
    ps.setString(1, pn);
    ps.setString(2, d);
    ps.setString(3, tname);
    ps.setString(4, tno);
    ps.setString(5, fr);
    ps.setString(6, to);
    ps.setString(7, de);
    ps.setString(8, ar);
    ps.setString(9, co);
    ps.setString(10, tt);
    int i=ps.executeUpdate();
    if(i==1)
    {
        JOptionPane.showMessageDialog(null,"booking is done");
        this.dispose();
        home h=new home();
        h.setVisible(true);
    }
}
catch (Exception e)
{
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
wallet w=new wallet();
w.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
/*
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(journeyplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(journeyplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(journeyplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(journeyplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new journeyplan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf13;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
